# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=256, verbose_name='Код факультета')),
                ('verbose', models.CharField(blank=True, default='', max_length=256, verbose_name='Название факультета')),
                ('lines', models.CharField(blank=True, default='', max_length=65536, verbose_name='Коды специальностей')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('code', models.CharField(blank=True, default='', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Код специальности')),
                ('verbose', models.CharField(blank=True, default='', max_length=256, unique=True, verbose_name='Название специальности')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Faculty', verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Код в базе')),
                ('verbose', models.CharField(blank=True, default='', max_length=256, unique=True, verbose_name='Полное название на русском')),
                ('city', models.CharField(blank=True, default='', max_length=256, verbose_name='Город')),
                ('faculties', models.CharField(blank=True, default='', max_length=65536, verbose_name='Коды факультетов')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.University', verbose_name='Университет'),
        ),
    ]
